name: underfoot_mobile
description: "Underfoot Underground Travel Planner - Find hidden gems"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
